### ISSUE TITLE
Upgrade NuGet packages

### ISSUE THREAD

**Issue by SeanFarrow** [justeat/JustBehave#16]
Hi,

Would it be possible to upgrade the NuGet packages JustBehave uses. Also, whilst doing this, could a dependency be taken on the IFixture interface, rather than the concrete fixture class from AutoFixture.

**Comment by AnthonySteele** [comment]
With the updates, are you thinking specifically of  AutoFixture? latest version is 3.36.10 and we are using 3.34.2 here.

**Comment by SeanFarrow** [comment]
Yep, also, There is an Nlog update.
When updating to 3.36.10, JustBehave can’t seem to override the CustomizeAutoFixture method.
Cheers
Sean.

**Comment by martincostello** [comment]
Looks like this was completed quite a while ago now.
