### ISSUE TITLE
Split the XUnit and NUnit components in to separate packages/projects and clean up packages

### ISSUE THREAD

**Issue by SeanFarrow** [justeat/JustBehave#23]
Hi,

I am using JustBehave and use XUnit exclusively to do my testing.
Would it be possible to split the NUnit and XUnit components of JustBehave in to separate packages as taking a dependency on NUnit is meaning people are using this rather than our preferred testing framework.
Also, is shouldly really needed as a dependency?
I'm now doing the split as it's messing up some of my DI tests. Shat do you want ot do with the shouldly library? is this really needed?
Kind regards
Sean.

**Comment by shaynevanasperen** [comment]
Ideally, this wouldn't depend on ANY specific test framework. Kind of like how [BBDfy](https://github.com/TestStack/TestStack.BDDfy) works. In fact, this project should probably just be retired and have consumers switch to using TestStack.BDDfy.

**Comment by SeanFarrow** [comment]
Taht's true, although given that JustSaying uses this library and the library is being ported to .net core/standard, it probably makes sense to do this anyway.
