### ISSUE TITLE
Build this in .Net core

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/JustBehave#24]
JustBehave is used by JustSaying's tests, and we want to build these in .Net core.

**Comment by JosephWoodward** [comment]
AutoFixture is going to be an issue as it doesn't support .NET Standard yet (I believe they're waiting until .NET Standard 2.0)

https://icanhasdot.net/result?github=justeat~2FJustBehave

**Comment by slang25** [comment]
@JosephWoodward They are working on it, and it's now the top priority since the project has got new owners.

**Comment by JosephWoodward** [comment]
My mistake, looks like there's a branch here: https://github.com/AutoFixture/AutoFixture/pull/740

**Comment by JosephWoodward** [comment]
@slang25 Yeah, it needed new owners as it seemed to have gone stale, glad to see it's now a focus.

**Comment by martincostello** [comment]
I think #25 is starting the journey.

**Comment by slang25** [comment]
#26

**Comment by martincostello** [comment]
I guess this is imminently about to be done @slang25?
