### ISSUE TITLE
package version lockin

### ISSUE THREAD

**Issue by AnthonySteele** [justeat/JustBehave#8]
[Over here on nuget](https://www.nuget.org/packages/JustBehave/) the JustBehave package specifies that it depends upon AutoFixture v 3.16.5 **and only that version**. 

AutoFixture has of course moved on since then, so anyone using JustBehave, and AutoFixture and updating packages is going to have a bad time.

Does it absolutely need to be that version? If not,  I can update JustBehave to latest AutoFixture and other packages, and loosen the required version.

**Comment by petemounce** [comment]
No particular reason, just haven't updated.

I'd love some automation we can run in ci that would try to upgrade
dependencies and if tests pass, commit that.

--

**Comment by AnthonySteele** [comment]
Updating packages on this project is worthwhile (and easy) though note that AutoFixture [is the only dependency here](https://www.nuget.org/packages/JustBehave/) that doesn't have a `>=` before the version. That's going to be an ongoing issue if we leave it.

**Comment by AnthonySteele** [comment]
It's fixed now.
